### ISSUE TITLE
Integration does not load any entities or devices

### ISSUE THREAD

**Issue by RACMan2527** [MorneSaunders360/nh_nicehash#1]
For the past 6 months I have been using the RomRider NiceHash integration.
It stopped responding this past weekend, and I have been looking for a alternate, including use of the Home Assistant REST and the NiceHash API.  
I came upon your integration, recently added and updated, and installed.

Your integration seems to load (no errors in the interface), unfortunately "No devices or entities"

Here is an output of the log and an error related to the integration...hope it helps

Home Assistant version 2023.6.2

-=-===-=-=-=-=-=

Logger: homeassistant.components.sensor
Source: helpers/update_coordinator.py:258
Integration: Sensor (documentation, issues)
First occurred: 11:38:16 AM (1 occurrences)
Last logged: 11:38:16 AM

Error while setting up nh_nicehash platform for sensor
Traceback (most recent call last):
  File "/config/custom_components/nh_nicehash/coordinator.py", line 37, in fetch_data
    totalBalance = json.loads(my_accounts_json)['totalBalance'] | int
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 242, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nh_nicehash/coordinator.py", line 103, in fetch_data
    raise UpdateFailed(f"Error fetching data from NiceHash API: {e}")
homeassistant.helpers.update_coordinator.UpdateFailed: Error fetching data from NiceHash API: string indices must be integers, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 320, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/nh_nicehash/sensor.py", line 10, in async_setup_entry
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady: Error fetching data from NiceHash API: string indices must be integers, not 'str'

**Comment by MorneSaunders360** [comment]
Thank you for reaching out and for trying out my NiceHash integration for Home Assistant. Your feedback is invaluable as it helps us improve our service and offer better user experiences.

I understand the issue you're currently facing and sincerely apologize for the inconvenience. The error you encountered is a known issue and I'm actively working on fixing it. Part of the ongoing work is aimed at creating a device for each mining rig, which should significantly enhance the functionality of the integration.

With regard to the RomRider NiceHash integration, I understand the predicament. NiceHash's frequently changing API can indeed pose a challenge, and it's not uncommon for developers to encounter difficulties in keeping up. Rest assured, this is not a criticism of RomRider's work but rather an industry-wide challenge.

In the meantime, as I work on improving this integration, I would recommend checking for updates regularly. If you continue to encounter any other issues or have further queries, please don't hesitate to reach out.

Thank you for your patience and understanding.
